export const ITEM_ASSET_FILE_MAP = {
  "Cheese Burger": "cheeseburger.webp",
  "Beef Burger": "beefburger.webp",
  "Gluten Free Chips": "chips.jpg",
  "Egg Sausage Bap": "baconsausagebap.jpg",
  "Veggie Burger (Normal)": "vegie burger.jpg",
  "Veggie Burger (Gluten Free)": "vegie burger.jpg",
  "Bacon Sausage Bap": "baconsausagebap.jpg",
  "Bacon Egg Sausage Bap": "baconeggsausagebap.jfif",
  "Hot Dog": "hotdog.jpg",
  Rollover: "rollover hotdog.jpg",
  "Chicken Burger": "chicken burger.webp",
  Chips: "chips.jpg",
  "Chips + Cheese": "chips+cheese.jpg",
  "Chips + Curry": "chips+curry.webp",
  "Chips + Chilli": "chips+chilly.webp",
  "Jacket + Cheese": "jacket+cheese.jpg",
  "Jacket + Chilli": "jacket+chilly.webp",
  "Jacket + Curry": "jacket+curry.jpg",
  "Sausage Roll": "sausage roll.jfif",
  Pie: "pie.webp",
  "Steak Pasty": "steak pasty.jpg",
  "Cheese and Onion Pasty": "cheese and onion pasty.webp",
  "Kids Cheese Burger Meal": "kidscheeseburgermeal.avif",
  "Kids Chicken Chunk Meal": "kidschickenchunkmeal.jfif",
  "Kids Beef Burger Meal": "kidsbeefburgermeal.avif",
  "Kids Veggie Burger Meal": "vegie burger.jpg",
  "Kids Cold Lunch Box Meal": "kidscoldlunchboxmeal.jpg",
  "Kids Chicken Burger Meal": "kidschickenburgermeal.jpg",
  "Kids Cheese Pizza Meal": "kids cheese pizza.jpg",
  "Kids Pork Pizza Meal": "kids chickenpizza.jpg",
  "12 Inch Four Cheese Pizza": "four cheese pizza.webp",
  "12 Inch Pulled Pork Pizza": "pork pizza.jpg",
  "BBQ Pizza": "bbq pizza.jpg",
  "Vegan Pizza": "vegan pizza.jpg",
  "Chicken Strips": "chicken strips.jpg",
  "Chicken Skewers": "chicken skewers.jpg",
  Crisps: "crips.png",
  "Caramel Shortbread": "caramelshortbread.jpg",
  Brownie: "brownie.webp",
  "Rainbow Cupcake": "Rainbowcupcake.webp",
  "Cookie Dough Brownie": "cookiedoughbrownie.jpg",
  Donut: "donut.webp",
  "Sweets / Chocolate": "sweetschocolate.jpg",
  "Bottled Drink": "bottled drink.webp",
  "Bottled Still Water": "bottled water.jpeg",
  "Shmoo Milkshake": "shmoomilkshake.webp",
  "Fruit Shoot": "fruitshoot.jpg",
  "Flavoured Milk": "flavored milk.jpg",
  Slushy: "slushy.jpg",
  "Fizzy Drink": "fizzy drink.jpg",
  Tea: "tea.jpg",
  Latte: "latte.jpg",
  "Black Coffee": "blackcoffe.jpg",
  Cappuccino: "cappuccino.webp",
  "Flat White": "flatwhite.webp"
};

export function defaultAssetPathForItem(itemName) {
  const fileName = ITEM_ASSET_FILE_MAP[itemName];
  return fileName ? `/asset/${fileName}` : null;
}
